name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, edited]

env:
  NODE_VERSION: "18.x"
  REACT_APP_MINIO_ROOT_USER: ${{ secrets.REACT_APP_MINIO_ROOT_USER }}
  REACT_APP_MINIO_ROOT_PASSWORD: ${{ secrets.REACT_APP_MINIO_ROOT_PASSWORD }}

jobs:
  test-and-coverage:
    runs-on: ubuntu-20.04
    services:
      minio:
        image: minio/minio
        env:
          MINIO_ACCESS_KEY: access_key
          MINIO_SECRET_KEY: secret_key
          MINIO_REGION: us-east-1
        ports:
          - 9000:9000
        options: >-
          --name minio
          --network test-net
          --network-alias minio
    steps:
      - uses: actions/checkout@v3
      - name: Debug environment variables
        run: |
          echo "NODE_VERSION: $NODE_VERSION"
          echo "REACT_APP_MINIO_ROOT_USER: $REACT_APP_MINIO_ROOT_USER"
          echo "REACT_APP_MINIO_ROOT_PASSWORD: $REACT_APP_MINIO_ROOT_PASSWORD"
          echo "REACT_APP_MINIO_ENDPOINT: $REACT_APP_MINIO_ENDPOINT"
      - name: Set up Typescript
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci
      - name: Test with Jest
        env:
          REACT_APP_MINIO_ENDPOINT: http://minio:9000
        run: |
          npm run test -- --coverage --runInBand --testResultsProcessor=jest-sonar-reporter
      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: test-report.xml
          retention-days: 7
      - name: Upload coverage report artifact pt2
        uses: actions/upload-artifact@v3
        with:
          name: coverage-lcov
          path: coverage/lcov.info
          retention-days: 7
    networks:
      test-net:
        driver: bridge

  sonarqube:
    # runs after test-and-coverage job
    needs: test-and-coverage
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Download coverage report artifact
        uses: actions/download-artifact@v3
        with:
          name: coverage-report
      - name: Download coverage report artifact pt2
        uses: actions/download-artifact@v3
        with:
          name: coverage-lcov

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}