name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, edited]

env:
  NODE_VERSION: "18.x"
  MINIO_ROOT_USER: ${{ secrets.REACT_APP_MINIO_ROOT_USER }}
  MINIO_ROOT_PASSWORD: ${{ secrets.REACT_APP_MINIO_ROOT_USER }}

jobs:
  test-and-coverage:
    runs-on: ubuntu-20.04
    services:
      minio:
        image: minio/minio:RELEASE.2023-03-24T21-41-23Z
        ports:
          - 9000:9000
        env:
          MINIO_ACCESS_KEY: ${{ env.MINIO_ROOT_USER }}
          MINIO_SECRET_KEY: ${{ env.MINIO_ROOT_PASSWORD }}
        options: >-
          --health-cmd "curl -f http://localhost:9000/minio/health/live"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2

      - name: Set up Typescript
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Test with Jest
        run: |
          npm run test -- --coverage --runInBand --testResultsProcessor=jest-sonar-reporter
      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: test-report.xml
          retention-days: 7
      - name: Upload coverage report artifact pt2
        uses: actions/upload-artifact@v2
        with:
          name: coverage-lcov
          path: coverage/lcov.info
          retention-days: 7

  sonarqube:
    # runs after test-and-coverage job
    needs: test-and-coverage
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Download coverage report artifact
        uses: actions/download-artifact@v2
        with:
          name: coverage-report
      - name: Download coverage report artifact pt2
        uses: actions/download-artifact@v2
        with:
          name: coverage-lcov

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
