name: Lints

on:
  push:
    branches: ['*']

env:
  NODE_VERSION: "18.x"

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name : Set up Typescript
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm install
      - name: Lint with ESLint
        run: |
          npm run lint
